### ISSUE TITLE
last_insert_id ?

### ISSUE THREAD

**Issue by ionuthristodorescu** [mysql-otp/mysql-otp-poolboy#11]
Hi - how could I check the last_insert_id (https://dev.mysql.com/doc/refman/5.0/en/getting-unique-id.html) for a mysql_poolboy:execute() command ?

**Comment by RaoH** [comment]
The correct way is to use mysql_poolboy:with/2 (or transaction/2) where you have a fun which accepts a connection.
With that connection (which is a mysql/otp connection) you can call  mysql:insert_id(Conn).

Alternatively you could checkout a connection from the pool and do the mysql:query(Conn, ...) and use mysql:insert_id(Conn)

**Comment by ionuthristodorescu** [comment]
Perfect.
