### ISSUE TITLE
rebar.config and Makefile mysql-otp mismatch 

### ISSUE THREAD

**Issue by everydaysasaturday** [mysql-otp/mysql-otp-poolboy#18]
in release 0.1.7

rebar.config has mysql-otp version 1.2.0 defined
Makefile has mysql-otp version 1.1.1 defined

is this intentional or for some other reason why the versions mismatch?

**Comment by zuiderkwast** [comment]
This is not intentional. Some automated test to check that these versions match would be cool. PR is welcome.

**Comment by zuiderkwast** [comment]
Fixed. Also updated dep version and this version now. (The version src/mysql_poolboy.app.src should match the current version git tag as well.)
