### ISSUE TITLE
Function name "checkout_connection" is too long

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp-poolboy#2]
I suggest these are renamed to shorter names `checkin` and `checkout` for convenience.

These are useful functions and it is not a problem if you sometimes forget to do checkin afterwards. Poolboy keeps a monitor on the user process so if it dies, the connection is returned to the pool. So at least for short-lived processes it is not a big deal if you forget to checkin. (For long-lived processes see #3.)

It is often necessary to do checkout to be able to do more than one thing on a connection. Examples: 1. Make an insert and afterwards use insert_it/1 to get the id of the inserted row. 2. Use warning_count/1 or any other of those functions after another query.

**Comment by RaoH** [comment]
Agree completely.
Was kinda stuck in the api model poolboy had in their example.
