### ISSUE TITLE
could you update rebar.config to point to the latest mysql-otp ? 

### ISSUE THREAD

**Issue by ionuthristodorescu** [mysql-otp/mysql-otp-poolboy#21]
thank you.

**Comment by zuiderkwast** [comment]
@ionuthristodorescu I have given you permissions to do it :-)

**Comment by lrascao** [comment]
i would also like that, can someone do it please?

**Comment by zuiderkwast** [comment]
It is the latest already (1.3.1) but there is no new version tag for mysql-otp-poolboy. You could use the master branch of this repo if you want the latest of the latest...

**Comment by lrascao** [comment]
yeah, that's what i'm doing right now, the thing is i would like a tag before going live with anything

**Comment by lrascao** [comment]
ping?

**Comment by zuiderkwast** [comment]
Done.
