### ISSUE TITLE
with/2 for checkout-Fun()-checkin without SQL transaction

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp-poolboy#3]
Actually also cowboy is also using a pool so it can also reuse one process for another http connection so even those processes are not short-lived ones. That means that it is important to checkin the mysql connection after usage, which normally has to be in a try-after block to be sure it is not forgotten, i.e.

```Erlang
Conn = mysql_poolboy:checkout(mypool),
try
    mysql:query(Conn, "SELECT INSERT BLA BLA BLA")
after
    mysql_poolboy:checking(mypool, Conn)
end.
```

so we can wrap this in a `with/2` which I imagine is a wrapper for `poolboy:transaction/2` but it's not an SQL transaction so calling it a transaction could be confusing. I suggest the name "with" which is a construct in python for doing the equivallent of try-after with a resource like this.

```Erlang
mysql_poolboy:with(mypool, fun (Conn) -> mysql:query(Conn, "SELECT BLA BLA") end).
```

**Comment by RaoH** [comment]
Fixed in 3df1072
