### ISSUE TITLE
execute/3,4 for prepared statements

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp-poolboy#4]
```Erlang
mysql_poolboy:execute(mypool, mystmt, [1, 2]).
```

For this, we need to know that the statement is prepared on the actual connection that we get from the pool. This can be solved if a statement is prepared directly when a connection is opened. For this we need an option for `mysql:start_link/1` like `{prepare, [...]}`. That would have to be fixed in mysql-otp first.

```Erlang
Prepare = [{mystmt, "INSERT INTO tardis (doctor, dalek) VALUES (?, ?)"},
           {blabla, "SELECT doctor FROM tardis WHERE dalek = ?"}],
{ok, Pid} = mysql:start_link([{user, "aladdin"},
                              {password, "sesame"},
                              {prepare, Prepare}].
```

**Comment by RaoH** [comment]
Not fixable here but already done in https://github.com/mysql-otp/mysql-otp/commit/f43a6a777f0ec83bbba9435cb6aa1b97cc67323d

**Comment by RaoH** [comment]
Whoops...
We do need execute/3,4 in this project though. Reopening!
